// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekSiparisi.Api.Data;

#nullable disable

namespace YemekSiparisi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512111127_AddKomurhanKavurma")]
    partial class AddKomurhanKavurma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YemekSiparisi.Api.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 70,
                            Category = "Spesiyaller",
                            Description = "Kömürhan'ın dünyaca ünlü, lokum gibi kuzu kavurması.",
                            ImageUrl = "https://images.unsplash.com/photo-1603360946369-dc9bb6258143",
                            IsInStock = true,
                            Name = "Kömürhan Kavurma",
                            Price = 1350m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 71,
                            Category = "Spesiyaller",
                            Description = "Bütün kuzu kafes, özel fırınlama tekniği ile.",
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947",
                            IsInStock = true,
                            Name = "Kuzu Kafes",
                            Price = 4400m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 72,
                            Category = "Spesiyaller",
                            Description = "Kalbur usulü fıstıklı ve özel zırh kıymalı.",
                            ImageUrl = "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0",
                            IsInStock = true,
                            Name = "Kalbur Burma Kebap",
                            Price = 1150m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 73,
                            Category = "Spesiyaller",
                            Description = "Fırında kaşar peyniri ile harmanlanmış kavurma.",
                            ImageUrl = "https://images.unsplash.com/photo-1603360946369-dc9bb6258143",
                            IsInStock = true,
                            Name = "Kiremitte Kaşarlı Kavurma",
                            Price = 1350m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 74,
                            Category = "Spesiyaller",
                            Description = "Özel sos ve yoğurt eşliğinde fırınlanmış beyti.",
                            ImageUrl = "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
                            IsInStock = true,
                            Name = "Fırın Beyti",
                            Price = 920m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 75,
                            Category = "Kebaplar",
                            Description = "Klasik Adana lezzeti, közlenmiş sebzelerle.",
                            ImageUrl = "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0",
                            IsInStock = true,
                            Name = "Adana Kebap",
                            Price = 750m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 76,
                            Category = "Kırmızı Etler",
                            Description = "Kuzunun en özel ve yumuşak yeri.",
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947",
                            IsInStock = true,
                            Name = "Küşleme",
                            Price = 1340m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 77,
                            Category = "Salatalar",
                            Description = "Taptaze mevsim sebzeleri ve özel şef sosu.",
                            ImageUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd",
                            IsInStock = true,
                            Name = "Şefin Salatası",
                            Price = 500m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 78,
                            Category = "Mezeler",
                            Description = "Cevizli ve nar ekşili nefis meze.",
                            ImageUrl = "https://images.unsplash.com/photo-1541529086526-db283c563270",
                            IsInStock = true,
                            Name = "Muhammara",
                            Price = 330m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 79,
                            Category = "İçecekler",
                            Description = "Bol köpüklü, doğal yayık ayranı.",
                            ImageUrl = "https://images.unsplash.com/photo-1571328003758-4a3921661709",
                            IsInStock = true,
                            Name = "Yayık Ayran",
                            Price = 60m,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 51,
                            Category = "Ana Yemekler",
                            Description = "Tavuk, Kıyma, Kuşbaşı etlerinin muhteşem buluşması.",
                            ImageUrl = "https://images.unsplash.com/photo-1626074353765-517a681e40be",
                            IsInStock = true,
                            Name = "1.5 Karışık Izgara",
                            Price = 1125m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 52,
                            Category = "Ana Yemekler",
                            Description = "Fırında taze alabalık, üzerine erimiş kaşar peyniri.",
                            ImageUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
                            IsInStock = true,
                            Name = "Kiremitte Kaşarlı Alabalık",
                            Price = 410m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 53,
                            Category = "Ana Yemekler",
                            Description = "Özel baharatlarla hazırlanan zırh kıyması.",
                            ImageUrl = "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0",
                            IsInStock = true,
                            Name = "Adana Kebap (Tek Şiş)",
                            Price = 230m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 54,
                            Category = "Ana Yemekler",
                            Description = "Lokum gibi kuzu kuşbaşı.",
                            ImageUrl = "https://images.unsplash.com/photo-1544025162-d76694265947",
                            IsInStock = true,
                            Name = "Kuşbaşı Kebap (Tek Şiş)",
                            Price = 250m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 55,
                            Category = "Ana Yemekler",
                            Description = "Taze balık eti, yeşillik ve özel sos ile.",
                            ImageUrl = "https://images.unsplash.com/photo-1554522723-b2a47cb105e3",
                            IsInStock = true,
                            Name = "Balık Dürüm",
                            Price = 250m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 56,
                            Category = "Çorbalar",
                            Description = "Sıcacık, ev yapımı tadında.",
                            ImageUrl = "https://images.unsplash.com/photo-1547592166-23ac45744acd",
                            IsInStock = true,
                            Name = "Mercimek Çorbası",
                            Price = 130m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 57,
                            Category = "Tatlılar",
                            Description = "Sıcak servis edilen enfes tahin helvası.",
                            ImageUrl = "https://images.unsplash.com/photo-1579372781875-66bbaf22c702",
                            IsInStock = true,
                            Name = "Fırın Helva",
                            Price = 150m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 58,
                            Category = "Tatlılar",
                            Description = "Bol peynirli, çıtır çıtır.",
                            ImageUrl = "https://images.unsplash.com/photo-1571115177098-24ec42ed2bb4",
                            IsInStock = true,
                            Name = "Künefe",
                            Price = 200m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 59,
                            Category = "İçecekler",
                            Description = "Buz gibi, bol köpüklü.",
                            ImageUrl = "https://images.unsplash.com/photo-1571328003758-4a3921661709",
                            IsInStock = true,
                            Name = "Yayık Ayran",
                            Price = 35m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 60,
                            Category = "İçecekler",
                            Description = "Közde ağır ağır pişmiş.",
                            ImageUrl = "https://images.unsplash.com/photo-1544787210-22bb1e8163ee",
                            IsInStock = true,
                            Name = "Türk Kahvesi",
                            Price = 80m,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 1,
                            Category = "Kebap",
                            Description = "Zırh kıyması, közlenmiş biber ile.",
                            DiscountPrice = 200m,
                            ImageUrl = "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500",
                            IsInStock = true,
                            Name = "Adana Kebap",
                            Price = 250m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Kebap",
                            Description = "Çıtır Antep lahmacunu.",
                            DiscountPrice = 65m,
                            ImageUrl = "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500",
                            IsInStock = true,
                            Name = "Lahmacun",
                            Price = 80m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pizza",
                            Description = "Mozzarella ve taze fesleğen.",
                            DiscountPrice = 149m,
                            ImageUrl = "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500",
                            IsInStock = true,
                            Name = "Margarita Pizza",
                            Price = 180m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "Pizza",
                            Description = "Bol malzemeli İtalyan usulü.",
                            DiscountPrice = 190m,
                            ImageUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
                            IsInStock = true,
                            Name = "Karışık Pizza",
                            Price = 220m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Category = "Burger",
                            Description = "180gr köfte ve cheddar.",
                            DiscountPrice = 199m,
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            IsInStock = true,
                            Name = "Classic Burger",
                            Price = 220m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 6,
                            Category = "Burger",
                            Description = "Özel soslu dev burger.",
                            DiscountPrice = 240m,
                            ImageUrl = "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
                            IsInStock = true,
                            Name = "Dumanlı Special",
                            Price = 280m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = "Tatlı",
                            Description = "Gaziantep usulü bol fıstıklı.",
                            DiscountPrice = 120m,
                            ImageUrl = "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=500",
                            IsInStock = true,
                            Name = "Fıstıklı Baklava",
                            Price = 150m,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 8,
                            Category = "Tatlı",
                            Description = "Fırınlanmış tam kıvamında.",
                            ImageUrl = "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=500",
                            IsInStock = true,
                            Name = "Sütlaç",
                            Price = 70m,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 9,
                            Category = "Deniz Mahsulleri",
                            Description = "Salata ve garnitür ile.",
                            DiscountPrice = 290m,
                            ImageUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500",
                            IsInStock = true,
                            Name = "Izgara Çupra",
                            Price = 350m,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 10,
                            Category = "Yeşil Bahçe",
                            Description = "Sağlıklı ve doyurucu.",
                            ImageUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
                            IsInStock = true,
                            Name = "Kinoa Salatası",
                            Price = 120m,
                            RestaurantId = 6
                        });
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Çarşı Merkezi, No: 44",
                            CreatedAt = new DateTime(2026, 5, 12, 14, 11, 26, 413, DateTimeKind.Local).AddTicks(5099),
                            Description = "En lezzetli kebaplar ve lahmacunlar.",
                            LogoUrl = "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0",
                            Name = "Gaziantep Kebapçısı",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cumhuriyet Cad. No: 12",
                            CreatedAt = new DateTime(2026, 5, 12, 14, 11, 26, 413, DateTimeKind.Local).AddTicks(5115),
                            Description = "Gerçek odun ateşinde İtalyan pizzası.",
                            LogoUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591",
                            Name = "İtalyan Pizza Dünyası",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bahçelievler Mah. No: 7",
                            CreatedAt = new DateTime(2026, 5, 12, 14, 11, 26, 413, DateTimeKind.Local).AddTicks(5118),
                            Description = "Gurme burger ve özel soslar.",
                            LogoUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd",
                            Name = "Dumanlı Burger",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kanalboyu Cad. No: 21",
                            CreatedAt = new DateTime(2026, 5, 12, 14, 11, 26, 413, DateTimeKind.Local).AddTicks(5121),
                            Description = "Geleneksel ve modern tatlılar.",
                            LogoUrl = "https://images.unsplash.com/photo-1551024601-bec78aea704b",
                            Name = "Tatlı Köşesi",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 5,
                            Address = "Fahri Kayahan No: 88",
                            CreatedAt = new DateTime(2026, 5, 12, 14, 11, 26, 413, DateTimeKind.Local).AddTicks(5125),
                            Description = "Taze balık ve deniz mahsulleri.",
                            LogoUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2",
                            Name = "Ege Deniz Restoran",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Address = "Yeşilyurt Mah. Doğa Cad. No: 12",
                            CreatedAt = new DateTime(2026, 5, 12, 14, 11, 26, 413, DateTimeKind.Local).AddTicks(5127),
                            Description = "Doğadan sofranıza taze sebze ve meyveler.",
                            LogoUrl = "https://images.unsplash.com/photo-1540420773420-3366772f4999",
                            Name = "Yeşil Bahçe",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 7,
                            Address = "Kanalboyu Cad. No: 45, Malatya",
                            CreatedAt = new DateTime(2026, 5, 12, 14, 11, 26, 413, DateTimeKind.Local).AddTicks(5131),
                            Description = "Malatya'nın eşsiz lezzetleri, taze ve doğal ürünlerle Ali Dayı farkıyla.",
                            LogoUrl = "https://images.unsplash.com/photo-1626074353765-517a681e40be",
                            Name = "Malatya Ali Dayının Yeri",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 8,
                            Address = "Malatya-Elazığ Yolu, Kömürhan Mevkii",
                            CreatedAt = new DateTime(2026, 5, 12, 14, 11, 26, 413, DateTimeKind.Local).AddTicks(5133),
                            Description = "Efsane Kömürhan kavurması ve Elazığ'ın yöresel et lezzetleri.",
                            LogoUrl = "https://images.unsplash.com/photo-1544025162-d76694265947",
                            Name = "Elazığ Kömürhan Kavurma",
                            Rating = 4.9000000000000004
                        });
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Coupon", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Favorite", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparisi.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.MenuItem", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Notification", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Order", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSiparisi.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.OrderItem", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparisi.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Restaurant", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
