// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YemekSiparisi.Api.Data;

#nullable disable

namespace YemekSiparisi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YemekSiparisi.Api.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kebap",
                            Description = "Zırh kıyması, közlenmiş biber ile.",
                            DiscountPrice = 200m,
                            ImageUrl = "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500",
                            IsInStock = true,
                            Name = "Adana Kebap",
                            Price = 250m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Kebap",
                            Description = "Çıtır Antep lahmacunu.",
                            DiscountPrice = 65m,
                            ImageUrl = "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500",
                            IsInStock = true,
                            Name = "Lahmacun",
                            Price = 80m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pizza",
                            Description = "Mozzarella ve taze fesleğen.",
                            DiscountPrice = 149m,
                            ImageUrl = "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500",
                            IsInStock = true,
                            Name = "Margarita Pizza",
                            Price = 180m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "Pizza",
                            Description = "Bol malzemeli İtalyan usulü.",
                            DiscountPrice = 190m,
                            ImageUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
                            IsInStock = true,
                            Name = "Karışık Pizza",
                            Price = 220m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 5,
                            Category = "Burger",
                            Description = "180gr köfte ve cheddar.",
                            DiscountPrice = 199m,
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            IsInStock = true,
                            Name = "Classic Burger",
                            Price = 220m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 6,
                            Category = "Burger",
                            Description = "Özel soslu dev burger.",
                            DiscountPrice = 240m,
                            ImageUrl = "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
                            IsInStock = true,
                            Name = "Dumanlı Special",
                            Price = 280m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = "Tatlı",
                            Description = "Gaziantep usulü bol fıstıklı.",
                            DiscountPrice = 120m,
                            ImageUrl = "https://images.unsplash.com/photo-1519676867240-f03562e64548?w=500",
                            IsInStock = true,
                            Name = "Fıstıklı Baklava",
                            Price = 150m,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 8,
                            Category = "Tatlı",
                            Description = "Fırınlanmış tam kıvamında.",
                            ImageUrl = "https://images.unsplash.com/photo-1516684732162-798a0062be99?w=500",
                            IsInStock = true,
                            Name = "Sütlaç",
                            Price = 70m,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 9,
                            Category = "Deniz Mahsulleri",
                            Description = "Salata ve garnitür ile.",
                            DiscountPrice = 290m,
                            ImageUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500",
                            IsInStock = true,
                            Name = "Izgara Çupra",
                            Price = 350m,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 10,
                            Category = "Yeşil Bahçe",
                            Description = "Sağlıklı ve doyurucu.",
                            ImageUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
                            IsInStock = true,
                            Name = "Kinoa Salatası",
                            Price = 120m,
                            RestaurantId = 6
                        });
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Çarşı Merkezi, No: 44",
                            CreatedAt = new DateTime(2026, 5, 12, 13, 6, 16, 606, DateTimeKind.Local).AddTicks(7608),
                            Description = "En lezzetli kebaplar ve lahmacunlar.",
                            LogoUrl = "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=500",
                            Name = "Gaziantep Kebapçısı",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cumhuriyet Cad. No: 12",
                            CreatedAt = new DateTime(2026, 5, 12, 13, 6, 16, 606, DateTimeKind.Local).AddTicks(7625),
                            Description = "Gerçek odun ateşinde İtalyan pizzası.",
                            LogoUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
                            Name = "İtalyan Pizza Dünyası",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bahçelievler Mah. No: 7",
                            CreatedAt = new DateTime(2026, 5, 12, 13, 6, 16, 606, DateTimeKind.Local).AddTicks(7628),
                            Description = "Gurme burger ve özel soslar.",
                            LogoUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
                            Name = "Dumanlı Burger",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kanalboyu Cad. No: 21",
                            CreatedAt = new DateTime(2026, 5, 12, 13, 6, 16, 606, DateTimeKind.Local).AddTicks(7632),
                            Description = "Geleneksel ve modern tatlılar.",
                            LogoUrl = "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=500",
                            Name = "Tatlı Köşesi",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 5,
                            Address = "Fahri Kayahan No: 88",
                            CreatedAt = new DateTime(2026, 5, 12, 13, 6, 16, 606, DateTimeKind.Local).AddTicks(7634),
                            Description = "Taze balık ve deniz mahsulleri.",
                            LogoUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500",
                            Name = "Ege Deniz Restoran",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Address = "İnönü Cad. No: 156",
                            CreatedAt = new DateTime(2026, 5, 12, 13, 6, 16, 606, DateTimeKind.Local).AddTicks(7637),
                            Description = "Sağlıklı salatalar ve vegan seçenekler.",
                            LogoUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
                            Name = "Yeşil Bahçe",
                            Rating = 4.4000000000000004
                        });
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Coupon", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Favorite", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparisi.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.MenuItem", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.Restaurant", "Restaurant")
                        .WithMany("MenuItems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Order", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YemekSiparisi.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.OrderItem", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YemekSiparisi.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Restaurant", b =>
                {
                    b.HasOne("YemekSiparisi.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("YemekSiparisi.Api.Models.Restaurant", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
